$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: project_dictionary
    path: "./.cspell/dictionary.txt"
    addWords: true
dictionaries:
  - project_dictionary
ignorePaths:
  - ".cspell"
  - "target"
