// Objective-C API for talking to go.trulyao.dev/youcast Go package.
//   gobind -lang=objc go.trulyao.dev/youcast
//
// File is generated by gobind. Do not edit.

#ifndef __Core_H__
#define __Core_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CoreCore;

@interface CoreCore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

FOUNDATION_EXPORT NSString* _Nonnull CoreExtractVideoID(NSString* _Nullable url, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT CoreCore* _Nullable CoreNew(void);

#endif
