[tools]
go = "1.23.0"

[tasks."build:core"]
description = "Build xcframework for iOS using gomobile"
# run = "gomobile bind -o ../Core.xcframework -target=ios -ldflags=-w -v"
run = "gomobile bind -v -o ../YouCast/Core.xcframework -target=ios,iossimulator -ldflags=-w ."
dir = "./"
