
// Objective-C API for talking to the following Go packages
//
//	go.trulyao.dev/youcast
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Core_FRAMEWORK_H__
#define __Core_FRAMEWORK_H__

#include "Youcast.objc.h"
#include "Universe.objc.h"

#endif
