// Objective-C API for talking to go.trulyao.dev/youcast Go package.
//   gobind -lang=objc go.trulyao.dev/youcast
//
// File is generated by gobind. Do not edit.

#ifndef __Core_H__
#define __Core_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CoreCore;

@interface CoreCore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)extractVideoID:(NSString* _Nullable)url error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT CoreCore* _Nullable CoreNew(void);

#endif
