// Objective-C API for talking to go.trulyao.dev/youcast Go package.
//   gobind -lang=objc go.trulyao.dev/youcast
//
// File is generated by gobind. Do not edit.

#ifndef __Youcast_H__
#define __Youcast_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class YoucastCore;

@interface YoucastCore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

FOUNDATION_EXPORT YoucastCore* _Nullable YoucastNew(void);

#endif
