/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PreviewLazyImport = createFileRoute('/preview')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PreviewLazyRoute = PreviewLazyImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/preview.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/preview': typeof PreviewLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/preview': typeof PreviewLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/preview': typeof PreviewLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preview'
  id: '__root__' | '/' | '/preview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PreviewLazyRoute: typeof PreviewLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PreviewLazyRoute: PreviewLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/preview"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/preview": {
      "filePath": "preview.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
