// Objective-C API for talking to go.trulyao.dev/youcast Go package.
//   gobind -lang=objc go.trulyao.dev/youcast
//
// File is generated by gobind. Do not edit.

#ifndef __Core_H__
#define __Core_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "List.objc.h"

@class CoreCore;
@class CorePlaylistMeta;
@class CoreVideoMeta;

@interface CoreCore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)extractVideoID:(NSString* _Nullable)url error:(NSError* _Nullable* _Nullable)error;
- (CorePlaylistMeta* _Nullable)getPlaylistMeta:(NSString* _Nullable)url error:(NSError* _Nullable* _Nullable)error;
- (CoreVideoMeta* _Nullable)getVideoMeta:(NSString* _Nullable)url error:(NSError* _Nullable* _Nullable)error;
@end

@interface CorePlaylistMeta : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull title;
@property (nonatomic) NSString* _Nonnull description;
@property (nonatomic) NSString* _Nonnull author;
@property (nonatomic) ListPlaylistEntryList* _Nullable videos;
/**
 * GetHighestResolution returns the first non-empty thumbnail with the highest resolution
 */
- (ListThumbnail* _Nullable)getFirstNonEmptyThumbnail;
- (int64_t)getTotalDurationMs;
@end

@interface CoreVideoMeta : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull title;
@property (nonatomic) NSString* _Nonnull description;
@property (nonatomic) NSString* _Nonnull author;
@property (nonatomic) NSString* _Nonnull channelID;
@property (nonatomic) NSString* _Nonnull channelHandle;
@property (nonatomic) long views;
@property (nonatomic) int64_t durationMs;
@property (nonatomic) int64_t unixPublishDate;
@property (nonatomic) ListFormatList* _Nullable formats;
@property (nonatomic) ListThumbnailList* _Nullable thumbnails;
@end

FOUNDATION_EXPORT CoreCore* _Nullable CoreNew(void);

#endif
