// Objective-C API for talking to go.trulyao.dev/youcast/list Go package.
//   gobind -lang=objc go.trulyao.dev/youcast/list
//
// File is generated by gobind. Do not edit.

#ifndef __List_H__
#define __List_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ListFormat;
@class ListFormatList;
@class ListPlaylistEntry;
@class ListPlaylistEntryList;
@class ListThumbnail;
@class ListThumbnailList;
@protocol ListFormatIterator;
@class ListFormatIterator;
@protocol ListPlaylistEntryIterator;
@class ListPlaylistEntryIterator;
@protocol ListThumbnailIterator;
@class ListThumbnailIterator;

@protocol ListFormatIterator <NSObject>
- (void)yield:(ListFormat* _Nullable)format;
@end

@protocol ListPlaylistEntryIterator <NSObject>
- (void)yield:(ListPlaylistEntry* _Nullable)entry;
@end

@protocol ListThumbnailIterator <NSObject>
- (void)yield:(ListThumbnail* _Nullable)p0;
@end

/**
 * Gomobile requires this wrapper since slices of structs are not supported at the moment
 */
@interface ListFormat : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long itag;
@property (nonatomic) NSString* _Nonnull url;
@property (nonatomic) NSString* _Nonnull mimeType;
@property (nonatomic) NSString* _Nonnull quality;
@property (nonatomic) long bitrate;
@property (nonatomic) long fps;
@property (nonatomic) long width;
@property (nonatomic) long height;
@property (nonatomic) NSString* _Nonnull lastModified;
@property (nonatomic) int64_t contentLength;
@property (nonatomic) NSString* _Nonnull qualityLabel;
@property (nonatomic) NSString* _Nonnull projectionType;
@property (nonatomic) long averageBitrate;
@property (nonatomic) NSString* _Nonnull audioQuality;
@property (nonatomic) int64_t approxDurationMs;
@property (nonatomic) NSString* _Nonnull audioSampleRate;
@property (nonatomic) long audioChannels;
@end

/**
 * Gomobile requires this wrapper since slices of structs are not supported at the moment
 */
@interface ListFormatList : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * Format list
 */
- (nullable instancetype)init;
// skipped method FormatList.Add with unsupported parameter or return types

- (ListFormatList* _Nullable)clear;
- (long)count;
// skipped method FormatList.From with unsupported parameter or return types

- (ListFormat* _Nullable)get:(long)index;
- (void)iterate:(id<ListFormatIterator> _Nullable)iterator;
- (ListFormatList* _Nullable)remove:(long)index;
@end

/**
 * Gomobile requires this wrapper since slices of structs are not supported at the moment
 */
@interface ListPlaylistEntry : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull title;
@property (nonatomic) NSString* _Nonnull author;
@property (nonatomic) int64_t durationMs;
@property (nonatomic) ListThumbnailList* _Nullable thumbnails;
@end

/**
 * Gomobile requires this wrapper since slices of structs are not supported at the moment
 */
@interface ListPlaylistEntryList : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
// skipped method PlaylistEntryList.Add with unsupported parameter or return types

- (ListPlaylistEntryList* _Nullable)clear;
- (long)count;
// skipped method PlaylistEntryList.From with unsupported parameter or return types

- (ListPlaylistEntry* _Nullable)get:(long)index;
- (void)iterate:(id<ListPlaylistEntryIterator> _Nullable)iterator;
- (ListPlaylistEntryList* _Nullable)remove:(long)index;
@end

/**
 * Gomobile requires this wrapper since slices of structs are not supported at the moment
 */
@interface ListThumbnail : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long width;
@property (nonatomic) long height;
@property (nonatomic) NSString* _Nonnull sourceURL;
@end

/**
 * Gomobile requires this wrapper since slices of structs are not supported at the moment
 */
@interface ListThumbnailList : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * ThumbnailList
 */
- (nullable instancetype)init;
// skipped method ThumbnailList.Add with unsupported parameter or return types

/**
 * This is required for the Swift wrapper to work, only the pointer type for a struct will be generated
 */
- (ListThumbnailList* _Nullable)addPtr:(ListThumbnail* _Nullable)thumbnail;
- (ListThumbnailList* _Nullable)clear;
- (long)count;
- (ListThumbnail* _Nullable)first;
// skipped method ThumbnailList.From with unsupported parameter or return types

- (ListThumbnail* _Nullable)get:(long)index;
- (ListThumbnail* _Nullable)getHighestResolution;
- (void)iterate:(id<ListThumbnailIterator> _Nullable)iterator;
- (ListThumbnail* _Nullable)last;
- (ListThumbnailList* _Nullable)remove:(long)index;
@end

/**
 * Format list
 */
FOUNDATION_EXPORT ListFormatList* _Nullable ListNewFormatList(void);

FOUNDATION_EXPORT ListPlaylistEntryList* _Nullable ListNewPlaylistEntryList(void);

/**
 * ThumbnailList
 */
FOUNDATION_EXPORT ListThumbnailList* _Nullable ListNewThumbnailList(void);

@class ListFormatIterator;

@class ListPlaylistEntryIterator;

@class ListThumbnailIterator;

/**
 * Gomobile requires this wrapper since slices of structs are not supported at the moment
 */
@interface ListFormatIterator : NSObject <goSeqRefInterface, ListFormatIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)yield:(ListFormat* _Nullable)format;
@end

/**
 * Gomobile requires this wrapper since slices of structs are not supported at the moment
 */
@interface ListPlaylistEntryIterator : NSObject <goSeqRefInterface, ListPlaylistEntryIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)yield:(ListPlaylistEntry* _Nullable)entry;
@end

/**
 * Gomobile requires this wrapper since slices of structs are not supported at the moment
 */
@interface ListThumbnailIterator : NSObject <goSeqRefInterface, ListThumbnailIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)yield:(ListThumbnail* _Nullable)p0;
@end

#endif
